### ISSUE TITLE
     An error occurred while installing dependencies.

### ISSUE THREAD

**Issue by ilan-schemoul** [kadirahq/getstorybook#28]
Whenever I try `getstorybook` on a fresh Meteor project with `react` and `react-dom` : 
```
 • Installing dependencies. ✖

     An error occurred while installing dependencies.
```

No npm-debug.log on the root of my project nor in the location where global storybook is installed.

I don't have any proxy. Slow start works but I hope getstorybook gonna require all the Meteor css.

PS : I also `npm i`

**Comment by NitroBAY** [comment]
Did @arunoda also give up this repo.

**Comment by ilan-schemoul** [comment]
Please @arunoda

**Comment by jpb12** [comment]
I had this issue running on windows.  To see the actual error that's happening, edit lib/helpers.js to add a console.log(result) statement in on line 104.

In my case, this was an error with the spawnSync command, and was fixed by appening '.cmd' at the end of the command name.  So:

     result = spawnSync('npm', ['install'], { stdio: 'inherit' });

became:

    result = spawnSync('npm.cmd', ['install'], { stdio: 'inherit' });

I did this in the three places I found that were using the spawnSync command, two in lib/helpers.js and one in lib/has_yarn.js.

**Comment by usulpro** [comment]
I think we can close it since it's solved in #26 

I tested it on Windows and it works fine

@NitroBAY @jpb12 Please reopen this if you still have any issues with `getstorybook`

**Comment by bogdan-calapod** [comment]
I just had the same problem - Applied the fix from @jpb12 's comment and it worked.

Windows 10, npm -v 3.10.10, node v.6.9.5

**Comment by usulpro** [comment]
@mnmtanish How do you think, can we release the patch via `@kadira`?

**Comment by drumsapkota** [comment]
@jpb12 I tried your fix, but I am still getting this error
@bogdan-calapod 

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: @storybook/react@^2.21.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 3.0.0-rc.3, 3.0.0-rc.2, 3.0.0-rc.0, 3.0.0-alpha.4, 3.0.0-alpha.3, 3.0.0-alpha.1, 3.0.0-alpha.0
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'react_game'
npm ERR! notarget

npm ERR! Please include the following file with any support request:
npm ERR!     D:\adi\plural\react_game\npm-debug.log

 • Installing dependencies. ✖

     An error occurred while installing dependencies.

I am using create-react-app to bootstrap the app and then using the storybook

**Comment by veerjainATgmail** [comment]
was getting the above error.. later I tried, 

npm i -g @storybook/cli
cd my-react-app
getstorybook

it worked..

**Comment by dcu-sharepoint** [comment]
@jpb12  I'm trying to find the **"lib"** you mention where the command file's extension has to be fixed for the windows mode but I can't find any trace of the lib directory in the hello-world project folder. where is the /lib directory you are referring to?

Thanks

**Comment by jpb12** [comment]
@dcu-sharepoint 

https://github.com/storybooks/getstorybook/blob/master/lib/helpers.js

It will be in your node_modules folder.
